language: python
python:
  - "3.8"
install:
  - wget -q -O - https://dl-ssl.google.com/linux/linux_signing_key.pub | sudo apt-key add -
  - sudo sh -c 'echo "deb [arch=amd64] http://dl.google.com/linux/chrome/deb/ stable main" >> /etc/apt/sources.list.d/google-chrome.list'
  - sudo apt-get -y update
  - sudo apt-get install -y google-chrome-stable
  - sudo apt-get install -yqq unzip
  - wget -O /tmp/chromedriver.zip http://chromedriver.storage.googleapis.com/`curl -sS chromedriver.storage.googleapis.com/LATEST_RELEASE`/chromedriver_linux64.zip
  - sudo unzip /tmp/chromedriver.zip chromedriver -d /usr/local/bin/
  - export DISPLAY=:99
  - export EMAIL=zach199201@gmail.com
  - export PASSWORD=Password123456!
  - pip install -r requirements.txt
script: python -m pytest --log-cli-level=INFO